# Generated by Django 5.2 on 2025-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonneeCapteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.IntegerField()),
                ('spo2', models.FloatField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
